config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  devise_for :users
  resources :users
  get 'users/:id' => 'users#show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :events
  root "users#show"

  resources :event_attendances
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: "User"
    has_many :event_attendances, foreign_key: :attended_id
    has_many :attendants, through: :event_attendances, source: :attendant
    validates :creator_id, presence: true
    scope :past, ->(date = Time.now) { where("date <= ?", date) }
    scope :future, ->(date = Time.now) { where("date >= ?", date) }
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
    belongs_to :attendant, class_name: "User"
    belongs_to :attended, class_name: "Event"
  end

app/models/user.rb
class User < ApplicationRecord
  has_many :events_created, foreign_key: :creator_id, class_name: "Event"
  has_many :event_attendances, foreign_key: :attendant_id
  has_many :events_attended, through: :event_attendances, source: :attended
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_attendances_controller.rb
class EventAttendancesController < ApplicationController
    def new
        @event_attendance = EventAttendance.new()
    end
    
    def create
        @event_attendance = EventAttendance.new(event_attendance_params)
        @event = Event.find(params[:event_attendance][:attended_id])

        if @event_attendance.save
            redirect_to event_url(@event)
        else
            render :new, status: :unprocessable_entity
        end

    end

    private
    def event_attendance_params
        params.require(:event_attendance).permit(:attendant_id, :attended_id)
    end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def index
        @events = Event.all
        @signed_in = user_signed_in?
        @user = current_user
    end

    def new
        @event = current_user.events_created.new
    end
    
    def create
        @event = current_user.events_created.new(event_params)
    
        if @event.save
            redirect_to event_url(@event)
        else
            render :new, status: :unprocessable_entity
        end
    end

    def show
        @event = Event.find(params[:id])
        @user = current_user
    end

    private
    def event_params
        params.require(:event).permit(:location, :date)
    end
  
end

# bin/rails g migration CreateJoinTableAttendeeAttendedEvent users events

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
    class Responder < ActionController::Responder
      def to_turbo_stream
        controller.render(options.merge(formats: :html))
      rescue ActionView::MissingTemplate => error
        if get?
          raise error
        elsif has_errors? && default_action
          render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
          redirect_to navigation_location
        end
      end
    end
  
    self.responder = Responder
    respond_to :html, :turbo_stream
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
#   skip_before_action :verify_user, only: [:index]
    def show
        @user = current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/event_attendances/new.html.erb
<%= form_with model: @event_attendance do |form| %>
  <%# <%= form.submit("Submit!")%> 
<% end %>

<% if @event_attendance.errors.any? %>
    <ul>
    <% @event_attendance.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
<% end %>

app/views/events/index.html.erb
<% if @signed_in %>
    <%= button_to(
        "Log Out",
        destroy_user_session_path,
        method: :delete
    ) %>
    <%= button_to "Your events", user_path(@user), method: :get %>
<% end %>

<h1>All Events:</h1>

<h2>Future events:</h2>

<div style="display: flex; width: 80%; flex-wrap: wrap;">
<% @events.future.each_with_index do |e,i| %>
    <div style="display: flex; flex-direction: column; margin: 0.5em; padding: 0.5em; border: 1px solid grey;">
        <h3> Event #<%= (i+1) %>:</h3>
        <p> Location: <%= e.location %> </p>
        <%=  link_to "Details", event_path(e) %>
        <p> Date: <%= e.date %> </p>
        <% if !e.attendants.empty? %>
            <div>
            Attendees: 
            <% e.attendants.each do |a| %>
            <p>- <%= a.email %></p>
            <% end %>
            </div>
        <% end %>
        <%= button_to "Attend Event", event_attendances_path({ event_attendance: { attended_id: e.id, attendant_id: @user.id}} ), method: "post" %>
    </div>
<% end %>
</div>

<h2>Past events:</h2>
<div style="display: flex; width: 80%; flex-wrap: wrap; flex: 1;">
<% @events.past.each_with_index do |e,i| %>
    <div style="display: flex; flex-direction: column; margin: 0.5em; padding: 0.5em; border: 1px solid grey;">
        <h3> Event #<%= (i+1) %>:</h3>
        <p> Location: <%= e.location %> </p>
        <%=  link_to "Details", event_path(e) %>
        <p> Date: <%= e.date %> </p>
        <% if !e.attendants.empty? %>
            <div>
            Attendees: 
            <% e.attendants.each do |a| %>
            <p>- <%= a.email %></p>
            <% end %>
            </div>
            <% end %>
    </div>
<% end %>
</div>



    <h5> welcome <%= @user.email %> </h5>

app/views/events/new.html.erb
<%= form_with model: @event do |form| %>
  <%= form.label(:date, "Date:")%>
  <%= form.date_select(:date)%>
  <%= form.label(:location, "Location:")%>
  <%= form.text_field(:location)%>
  <%= form.submit("Submit!")%>
<% end %>

<% if @event.errors.any? %>
    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
<% end %>

app/views/events/show.html.erb
<%= button_to "Your events", user_path, method: :get %>

<h1>Event information: </h1>
<p>Created by: <%=@event.creator.email%></p>
<p>Location: <%= @event.location %></p>
<p>Date: <%= @event.date%></p>
<div>
    Attendees: 
    <% @event.attendants.each do |a| %>
    <p><%= a%></p>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div style="margin-bottom: 5em;"></div>
<%= button_to(
    "Log Out",
    destroy_user_session_path,
    method: :delete
) %>
<%= button_to "Create event", new_event_path, method: :get %>
<%= button_to "All events", events_path, method: :get%>

<h1>Events you have created:</h1>
<div style="display: flex; width: 80%; flex-wrap: wrap;">
<% @user.events_created.each_with_index do |e,i| %>
    <div style="display: flex; flex-direction: column; margin: 0.5em; padding: 0.5em; border: 1px solid grey;">
        <h3> Event #<%= (i+1) %>:</h3>
        <p> Location: <%= e.location %> </p>
        <%=  link_to "Details", event_path(e) %>
        <p> Date: <%= e.date %> </p>
        <% if !e.attendants.empty? %>
            <div>
            Attendees: 
            <% e.attendants.each do |a| %>
            <p>- <%= a.email %></p>
            <% end %>
            </div>
            <% end %>
    </div>
<% end %>
</div>
<h1>Events you will attend:</h1>
<div style="display: flex; width: 80%; flex-wrap: wrap;">
<% @user.events_attended.future.each_with_index do |e,i| %>
    <div style="display: flex; flex-direction: column; margin: 0.5em; padding: 0.5em; border: 1px solid grey;">
        <h3> Event #<%= (i+1) %>:</h3>
        <p> Location: <%= e.location %> </p>
        <%=  link_to "Details", event_path(e) %>
    </div>
<% end %>
</div>
<h1>Events you have attended:</h1>
<div style="display: flex; width: 80%; flex-wrap: wrap;">
<% @user.events_attended.past.each_with_index do |e,i| %>
    <div style="display: flex; flex-direction: column; margin: 0.5em; padding: 0.5em; border: 1px solid grey;">
        <h3> Event #<%= (i+1) %>:</h3>
        <p> Location: <%= e.location %> </p>
        <%=  link_to "Details", event_path(e) %>
    </div>
<% end %>
</div>


<h5> welcome <%= @user.email %> </h5>